### ISSUE TITLE
Hardware Hacking Hands-on Workshop

### ISSUE THREAD

**Issue by Javantea** [tecknicaltom/seattle-infosec-calendar#10]
Thursday, July 20, 2017 7:00 PM
SoDo MakerSpace; 1914 Occidental ave s; Seattle, WA
https://www.meetup.com/Seattle-Web-Security-Meetup/events/241376924/
Announced on the DC206 list by Blibbet.

**Comment by tecknicaltom** [comment]
dupe of #8, already fixed and on the calendar. I think the inconsistency with the name of the event is cause for some confusion.

**Comment by awgh** [comment]
Yeah, sorry, that was my fault.  We won't rename it again :)
