### ISSUE TITLE
SeaSec East Infosec Meetup

### ISSUE THREAD

**Issue by BrBr-Prime** [tecknicaltom/seattle-infosec-calendar#13]
https://www.meetup.com/SEASec-East/

Meets the 1st Tuesday of each month.

@SeaSecEast on Twitter for announcements

**Comment by tecknicaltom** [comment]
the SeaSec East meetings should already be automatically sync'ed into the calendar. Unfortunately, the organizer didn't continue to name the meetings in a way that identifies it well. For instance, on November 7, the event is on there with the name "Mod Pizza in Bellevue"
