### ISSUE TITLE
Potential source: TA3M

### ISSUE THREAD

**Issue by tecknicaltom** [tecknicaltom/seattle-infosec-calendar#4]
https://seattleprivacy.org/programs/ta3m/

**Comment by tecknicaltom** [comment]
* asked about subscribable calendar via twitter July 14 https://twitter.com/tecknicaltom/status/885910470011506688
* asked via email Aug 3

**Comment by Javantea** [comment]
Ta3m is back Jan 15. https://seattleprivacy.org/event/ta3m-jan-2018/
They now have a Google calendar. That should be enough, I hope. And if not, you can ask them to fix it.
